-- Seed all US universities as campuses with coordinates
-- Run with: sudo -u postgres psql -d campuscuts -f seed_campuses.sql

-- First, ensure lat/lng columns exist
ALTER TABLE campuses ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 6);
ALTER TABLE campuses ADD COLUMN IF NOT EXISTS longitude DECIMAL(10, 6);
CREATE INDEX IF NOT EXISTS idx_campuses_coordinates ON campuses(latitude, longitude);

-- Delete invalid entries
DELETE FROM campuses WHERE name IN ('GMAIL', 'ICLOUD');

-- Insert all universities with coordinates (ON CONFLICT DO UPDATE to add coordinates to existing)
INSERT INTO campuses (id, slug, name, city, state, timezone, latitude, longitude, "updatedAt")
VALUES
  (gen_random_uuid(), 'abilene-christian', 'Abilene Christian University', 'Abilene', 'TX', 'America/Chicago', 32.4621, -99.7125, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'air-force', 'United States Air Force Academy', 'Colorado Springs', 'CO', 'America/Denver', 38.9983, -104.8614, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'akron', 'University of Akron', 'Akron', 'OH', 'America/New_York', 41.0765, -81.5116, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'alabama', 'University of Alabama', 'Tuscaloosa', 'AL', 'America/Chicago', 33.2140, -87.5391, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'alabama-birmingham', 'University of Alabama at Birmingham', 'Birmingham', 'AL', 'America/Chicago', 33.5021, -86.8086, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'alabama-huntsville', 'University of Alabama in Huntsville', 'Huntsville', 'AL', 'America/Chicago', 34.7254, -86.6394, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'alabama-state', 'Alabama State University', 'Montgomery', 'AL', 'America/Chicago', 32.3644, -86.2956, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'albany', 'University at Albany SUNY', 'Albany', 'NY', 'America/New_York', 42.6866, -73.8237, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'american', 'American University', 'Washington', 'DC', 'America/New_York', 38.9377, -77.0880, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'amherst', 'Amherst College', 'Amherst', 'MA', 'America/New_York', 42.3709, -72.5170, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'appalachian-state', 'Appalachian State University', 'Boone', 'NC', 'America/New_York', 36.2137, -81.6746, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'arizona', 'University of Arizona', 'Tucson', 'AZ', 'America/Phoenix', 32.2319, -110.9501, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'arizona-state', 'Arizona State University', 'Tempe', 'AZ', 'America/Phoenix', 33.4242, -111.9281, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'arkansas', 'University of Arkansas', 'Fayetteville', 'AR', 'America/Chicago', 36.0686, -94.1748, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'army', 'United States Military Academy', 'West Point', 'NY', 'America/New_York', 41.3915, -73.9565, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'auburn', 'Auburn University', 'Auburn', 'AL', 'America/Chicago', 32.6034, -85.4808, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'ball-state', 'Ball State University', 'Muncie', 'IN', 'America/Indiana/Indianapolis', 40.2058, -85.4089, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'baylor', 'Baylor University', 'Waco', 'TX', 'America/Chicago', 31.5489, -97.1131, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'binghamton', 'Binghamton University', 'Binghamton', 'NY', 'America/New_York', 42.0897, -75.9694, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'boise-state', 'Boise State University', 'Boise', 'ID', 'America/Boise', 43.6030, -116.2030, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'boston-college', 'Boston College', 'Chestnut Hill', 'MA', 'America/New_York', 42.3355, -71.1685, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'boston-university', 'Boston University', 'Boston', 'MA', 'America/New_York', 42.3505, -71.1054, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'bowling-green', 'Bowling Green State University', 'Bowling Green', 'OH', 'America/New_York', 41.3787, -83.6495, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'brandeis', 'Brandeis University', 'Waltham', 'MA', 'America/New_York', 42.3659, -71.2594, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'brigham-young', 'Brigham Young University', 'Provo', 'UT', 'America/Denver', 40.2519, -111.6493, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'brown', 'Brown University', 'Providence', 'RI', 'America/New_York', 41.8268, -71.4025, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'buffalo', 'University at Buffalo', 'Buffalo', 'NY', 'America/New_York', 43.0008, -78.7890, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'butler', 'Butler University', 'Indianapolis', 'IN', 'America/Indiana/Indianapolis', 39.8407, -86.1698, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cal-poly', 'California Polytechnic State University', 'San Luis Obispo', 'CA', 'America/Los_Angeles', 35.3050, -120.6625, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cal-poly-pomona', 'Cal Poly Pomona', 'Pomona', 'CA', 'America/Los_Angeles', 34.0565, -117.8215, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cal-state-fullerton', 'CSU Fullerton', 'Fullerton', 'CA', 'America/Los_Angeles', 33.8829, -117.8869, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cal-state-la', 'CSU Los Angeles', 'Los Angeles', 'CA', 'America/Los_Angeles', 34.0664, -118.1684, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cal-state-long-beach', 'CSU Long Beach', 'Long Beach', 'CA', 'America/Los_Angeles', 33.7838, -118.1141, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cal-state-northridge', 'CSU Northridge', 'Northridge', 'CA', 'America/Los_Angeles', 34.2401, -118.5298, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'caltech', 'California Institute of Technology', 'Pasadena', 'CA', 'America/Los_Angeles', 34.1377, -118.1253, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'carnegie-mellon', 'Carnegie Mellon University', 'Pittsburgh', 'PA', 'America/New_York', 40.4433, -79.9436, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'case-western', 'Case Western Reserve University', 'Cleveland', 'OH', 'America/New_York', 41.5045, -81.6089, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'central-florida', 'University of Central Florida', 'Orlando', 'FL', 'America/New_York', 28.6024, -81.2001, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'central-michigan', 'Central Michigan University', 'Mount Pleasant', 'MI', 'America/Detroit', 43.5892, -84.7697, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'charleston', 'College of Charleston', 'Charleston', 'SC', 'America/New_York', 32.7841, -79.9372, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cincinnati', 'University of Cincinnati', 'Cincinnati', 'OH', 'America/New_York', 39.1329, -84.5150, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'clemson', 'Clemson University', 'Clemson', 'SC', 'America/New_York', 34.6765, -82.8374, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'coastal-carolina', 'Coastal Carolina University', 'Conway', 'SC', 'America/New_York', 33.7946, -79.0186, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'colorado', 'University of Colorado Boulder', 'Boulder', 'CO', 'America/Denver', 40.0076, -105.2659, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'colorado-state', 'Colorado State University', 'Fort Collins', 'CO', 'America/Denver', 40.5734, -105.0865, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'columbia', 'Columbia University', 'New York', 'NY', 'America/New_York', 40.8075, -73.9626, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'connecticut', 'University of Connecticut', 'Storrs', 'CT', 'America/New_York', 41.8077, -72.2540, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cornell', 'Cornell University', 'Ithaca', 'NY', 'America/New_York', 42.4534, -76.4735, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'creighton', 'Creighton University', 'Omaha', 'NE', 'America/Chicago', 41.2655, -95.9455, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'dartmouth', 'Dartmouth College', 'Hanover', 'NH', 'America/New_York', 43.7044, -72.2887, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'dayton', 'University of Dayton', 'Dayton', 'OH', 'America/New_York', 39.7403, -84.1796, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'delaware', 'University of Delaware', 'Newark', 'DE', 'America/New_York', 39.6780, -75.7506, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'denver', 'University of Denver', 'Denver', 'CO', 'America/Denver', 39.6780, -104.9614, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'depaul', 'DePaul University', 'Chicago', 'IL', 'America/Chicago', 41.9253, -87.6558, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'drake', 'Drake University', 'Des Moines', 'IA', 'America/Chicago', 41.6043, -93.6562, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'drexel', 'Drexel University', 'Philadelphia', 'PA', 'America/New_York', 39.9566, -75.1899, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'duke', 'Duke University', 'Durham', 'NC', 'America/New_York', 36.0014, -78.9382, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'duquesne', 'Duquesne University', 'Pittsburgh', 'PA', 'America/New_York', 40.4365, -79.9930, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'east-carolina', 'East Carolina University', 'Greenville', 'NC', 'America/New_York', 35.6076, -77.3661, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'eastern-michigan', 'Eastern Michigan University', 'Ypsilanti', 'MI', 'America/Detroit', 42.2505, -83.6238, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'emory', 'Emory University', 'Atlanta', 'GA', 'America/New_York', 33.7925, -84.3235, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'fau', 'Florida Atlantic University', 'Boca Raton', 'FL', 'America/New_York', 26.3729, -80.1014, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'fiu', 'Florida International University', 'Miami', 'FL', 'America/New_York', 25.7563, -80.3748, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'florida', 'University of Florida', 'Gainesville', 'FL', 'America/New_York', 29.6436, -82.3549, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'florida-state', 'Florida State University', 'Tallahassee', 'FL', 'America/New_York', 30.4419, -84.2985, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'fordham', 'Fordham University', 'Bronx', 'NY', 'America/New_York', 40.8615, -73.8854, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'fresno-state', 'CSU Fresno', 'Fresno', 'CA', 'America/Los_Angeles', 36.8134, -119.7485, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'george-mason', 'George Mason University', 'Fairfax', 'VA', 'America/New_York', 38.8316, -77.3081, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'george-washington', 'George Washington University', 'Washington', 'DC', 'America/New_York', 38.8997, -77.0486, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'georgetown', 'Georgetown University', 'Washington', 'DC', 'America/New_York', 38.9076, -77.0723, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'georgia', 'University of Georgia', 'Athens', 'GA', 'America/New_York', 33.9480, -83.3773, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'georgia-southern', 'Georgia Southern University', 'Statesboro', 'GA', 'America/New_York', 32.4221, -81.7837, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'georgia-state', 'Georgia State University', 'Atlanta', 'GA', 'America/New_York', 33.7530, -84.3853, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'georgia-tech', 'Georgia Institute of Technology', 'Atlanta', 'GA', 'America/New_York', 33.7756, -84.3963, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'gonzaga', 'Gonzaga University', 'Spokane', 'WA', 'America/Los_Angeles', 47.6669, -117.4022, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'harvard', 'Harvard University', 'Cambridge', 'MA', 'America/New_York', 42.3770, -71.1167, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'hawaii', 'University of Hawaii at Manoa', 'Honolulu', 'HI', 'Pacific/Honolulu', 21.2969, -157.8171, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'hofstra', 'Hofstra University', 'Hempstead', 'NY', 'America/New_York', 40.7140, -73.6007, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'holy-cross', 'College of the Holy Cross', 'Worcester', 'MA', 'America/New_York', 42.2377, -71.8083, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'houston', 'University of Houston', 'Houston', 'TX', 'America/Chicago', 29.7199, -95.3422, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'howard', 'Howard University', 'Washington', 'DC', 'America/New_York', 38.9225, -77.0197, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'illinois', 'University of Illinois', 'Champaign', 'IL', 'America/Chicago', 40.1020, -88.2272, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'illinois-chicago', 'University of Illinois Chicago', 'Chicago', 'IL', 'America/Chicago', 41.8719, -87.6484, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'indiana', 'Indiana University', 'Bloomington', 'IN', 'America/Indiana/Indianapolis', 39.1653, -86.5264, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'iowa', 'University of Iowa', 'Iowa City', 'IA', 'America/Chicago', 41.6611, -91.5302, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'iowa-state', 'Iowa State University', 'Ames', 'IA', 'America/Chicago', 42.0267, -93.6465, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'james-madison', 'James Madison University', 'Harrisonburg', 'VA', 'America/New_York', 38.4382, -78.8736, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'johns-hopkins', 'Johns Hopkins University', 'Baltimore', 'MD', 'America/New_York', 39.3299, -76.6205, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'kansas', 'University of Kansas', 'Lawrence', 'KS', 'America/Chicago', 38.9543, -95.2558, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'kansas-state', 'Kansas State University', 'Manhattan', 'KS', 'America/Chicago', 39.1836, -96.5717, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'kent-state', 'Kent State University', 'Kent', 'OH', 'America/New_York', 41.1494, -81.3418, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'kentucky', 'University of Kentucky', 'Lexington', 'KY', 'America/New_York', 38.0306, -84.5040, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'lehigh', 'Lehigh University', 'Bethlehem', 'PA', 'America/New_York', 40.6072, -75.3783, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'liberty', 'Liberty University', 'Lynchburg', 'VA', 'America/New_York', 37.3526, -79.1769, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'louisiana-state', 'Louisiana State University', 'Baton Rouge', 'LA', 'America/Chicago', 30.4133, -91.1800, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'louisville', 'University of Louisville', 'Louisville', 'KY', 'America/New_York', 38.2114, -85.7585, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'loyola-chicago', 'Loyola University Chicago', 'Chicago', 'IL', 'America/Chicago', 41.9988, -87.6579, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'loyola-marymount', 'Loyola Marymount University', 'Los Angeles', 'CA', 'America/Los_Angeles', 33.9693, -118.4191, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'marquette', 'Marquette University', 'Milwaukee', 'WI', 'America/Chicago', 43.0385, -87.9296, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'maryland', 'University of Maryland', 'College Park', 'MD', 'America/New_York', 38.9869, -76.9426, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'massachusetts', 'UMass Amherst', 'Amherst', 'MA', 'America/New_York', 42.3868, -72.5301, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'memphis', 'University of Memphis', 'Memphis', 'TN', 'America/Chicago', 35.1187, -89.9372, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'miami', 'University of Miami', 'Coral Gables', 'FL', 'America/New_York', 25.7213, -80.2794, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'miami-ohio', 'Miami University', 'Oxford', 'OH', 'America/New_York', 39.5089, -84.7318, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'michigan', 'University of Michigan', 'Ann Arbor', 'MI', 'America/Detroit', 42.2780, -83.7382, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'michigan-state', 'Michigan State University', 'East Lansing', 'MI', 'America/Detroit', 42.7018, -84.4822, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'minnesota', 'University of Minnesota', 'Minneapolis', 'MN', 'America/Chicago', 44.9740, -93.2277, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'mississippi', 'University of Mississippi', 'Oxford', 'MS', 'America/Chicago', 34.3647, -89.5381, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'mississippi-state', 'Mississippi State University', 'Starkville', 'MS', 'America/Chicago', 33.4552, -88.7902, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'missouri', 'University of Missouri', 'Columbia', 'MO', 'America/Chicago', 38.9404, -92.3277, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'mit', 'Massachusetts Institute of Technology', 'Cambridge', 'MA', 'America/New_York', 42.3601, -71.0942, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'montana', 'University of Montana', 'Missoula', 'MT', 'America/Denver', 46.8625, -113.9847, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'navy', 'United States Naval Academy', 'Annapolis', 'MD', 'America/New_York', 38.9822, -76.4838, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'nebraska', 'University of Nebraska-Lincoln', 'Lincoln', 'NE', 'America/Chicago', 40.8202, -96.7005, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'nevada', 'University of Nevada Reno', 'Reno', 'NV', 'America/Los_Angeles', 39.5450, -119.8171, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'nevada-las-vegas', 'University of Nevada Las Vegas', 'Las Vegas', 'NV', 'America/Los_Angeles', 36.1080, -115.1414, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'new-hampshire', 'University of New Hampshire', 'Durham', 'NH', 'America/New_York', 43.1348, -70.9344, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'new-mexico', 'University of New Mexico', 'Albuquerque', 'NM', 'America/Denver', 35.0844, -106.6189, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'new-mexico-state', 'New Mexico State University', 'Las Cruces', 'NM', 'America/Denver', 32.2801, -106.7508, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'north-carolina', 'UNC Chapel Hill', 'Chapel Hill', 'NC', 'America/New_York', 35.9049, -79.0469, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'north-carolina-state', 'NC State University', 'Raleigh', 'NC', 'America/New_York', 35.7872, -78.6705, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'north-texas', 'University of North Texas', 'Denton', 'TX', 'America/Chicago', 33.2100, -97.1488, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'northeastern', 'Northeastern University', 'Boston', 'MA', 'America/New_York', 42.3398, -71.0892, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'northern-illinois', 'Northern Illinois University', 'DeKalb', 'IL', 'America/Chicago', 41.9294, -88.7710, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'northwestern', 'Northwestern University', 'Evanston', 'IL', 'America/Chicago', 42.0565, -87.6753, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'notre-dame', 'University of Notre Dame', 'Notre Dame', 'IN', 'America/Indiana/Indianapolis', 41.7052, -86.2353, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'ohio', 'Ohio University', 'Athens', 'OH', 'America/New_York', 39.3246, -82.1018, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'ohio-state', 'Ohio State University', 'Columbus', 'OH', 'America/New_York', 40.0067, -83.0305, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'oklahoma', 'University of Oklahoma', 'Norman', 'OK', 'America/Chicago', 35.2058, -97.4457, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'oklahoma-state', 'Oklahoma State University', 'Stillwater', 'OK', 'America/Chicago', 36.1258, -97.0683, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'old-dominion', 'Old Dominion University', 'Norfolk', 'VA', 'America/New_York', 36.8851, -76.3055, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'oregon', 'University of Oregon', 'Eugene', 'OR', 'America/Los_Angeles', 44.0448, -123.0726, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'oregon-state', 'Oregon State University', 'Corvallis', 'OR', 'America/Los_Angeles', 44.5646, -123.2620, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'penn', 'University of Pennsylvania', 'Philadelphia', 'PA', 'America/New_York', 39.9522, -75.1932, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'penn-state', 'Penn State University', 'University Park', 'PA', 'America/New_York', 40.7982, -77.8599, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'pepperdine', 'Pepperdine University', 'Malibu', 'CA', 'America/Los_Angeles', 34.0367, -118.7092, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'pittsburgh', 'University of Pittsburgh', 'Pittsburgh', 'PA', 'America/New_York', 40.4444, -79.9608, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'princeton', 'Princeton University', 'Princeton', 'NJ', 'America/New_York', 40.3440, -74.6514, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'providence', 'Providence College', 'Providence', 'RI', 'America/New_York', 41.8403, -71.4359, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'purdue', 'Purdue University', 'West Lafayette', 'IN', 'America/Indiana/Indianapolis', 40.4237, -86.9212, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'rice', 'Rice University', 'Houston', 'TX', 'America/Chicago', 29.7174, -95.4018, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'richmond', 'University of Richmond', 'Richmond', 'VA', 'America/New_York', 37.5753, -77.5400, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'rochester', 'University of Rochester', 'Rochester', 'NY', 'America/New_York', 43.1289, -77.6301, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'rutgers', 'Rutgers University', 'New Brunswick', 'NJ', 'America/New_York', 40.5008, -74.4474, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'saint-louis', 'Saint Louis University', 'St Louis', 'MO', 'America/Chicago', 38.6359, -90.2342, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'san-diego', 'University of San Diego', 'San Diego', 'CA', 'America/Los_Angeles', 32.7714, -117.1936, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'san-diego-state', 'San Diego State University', 'San Diego', 'CA', 'America/Los_Angeles', 32.7757, -117.0719, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'san-francisco', 'University of San Francisco', 'San Francisco', 'CA', 'America/Los_Angeles', 37.7765, -122.4506, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'san-jose-state', 'San Jose State University', 'San Jose', 'CA', 'America/Los_Angeles', 37.3352, -121.8811, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'santa-clara', 'Santa Clara University', 'Santa Clara', 'CA', 'America/Los_Angeles', 37.3496, -121.9390, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'seton-hall', 'Seton Hall University', 'South Orange', 'NJ', 'America/New_York', 40.7424, -74.2470, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'smu', 'Southern Methodist University', 'Dallas', 'TX', 'America/Chicago', 32.8431, -96.7851, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'south-carolina', 'University of South Carolina', 'Columbia', 'SC', 'America/New_York', 33.9940, -81.0303, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'south-florida', 'University of South Florida', 'Tampa', 'FL', 'America/New_York', 28.0587, -82.4139, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'southern-california', 'University of Southern California', 'Los Angeles', 'CA', 'America/Los_Angeles', 34.0224, -118.2851, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'stanford', 'Stanford University', 'Stanford', 'CA', 'America/Los_Angeles', 37.4275, -122.1697, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'stony-brook', 'Stony Brook University', 'Stony Brook', 'NY', 'America/New_York', 40.9176, -73.1238, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'syracuse', 'Syracuse University', 'Syracuse', 'NY', 'America/New_York', 43.0392, -76.1351, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'tcu', 'Texas Christian University', 'Fort Worth', 'TX', 'America/Chicago', 32.7098, -97.3633, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'temple', 'Temple University', 'Philadelphia', 'PA', 'America/New_York', 39.9812, -75.1554, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'tennessee', 'University of Tennessee', 'Knoxville', 'TN', 'America/New_York', 35.9544, -83.9295, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'texas', 'University of Texas at Austin', 'Austin', 'TX', 'America/Chicago', 30.2849, -97.7341, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'texas-am', 'Texas A&M University', 'College Station', 'TX', 'America/Chicago', 30.6187, -96.3365, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'texas-state', 'Texas State University', 'San Marcos', 'TX', 'America/Chicago', 29.8883, -97.9389, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'texas-tech', 'Texas Tech University', 'Lubbock', 'TX', 'America/Chicago', 33.5843, -101.8783, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'toledo', 'University of Toledo', 'Toledo', 'OH', 'America/New_York', 41.6578, -83.6148, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'towson', 'Towson University', 'Towson', 'MD', 'America/New_York', 39.3927, -76.6093, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'tulane', 'Tulane University', 'New Orleans', 'LA', 'America/Chicago', 29.9398, -90.1205, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'tulsa', 'University of Tulsa', 'Tulsa', 'OK', 'America/Chicago', 36.1505, -95.9453, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-berkeley', 'UC Berkeley', 'Berkeley', 'CA', 'America/Los_Angeles', 37.8719, -122.2585, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-davis', 'UC Davis', 'Davis', 'CA', 'America/Los_Angeles', 38.5382, -121.7617, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-irvine', 'UC Irvine', 'Irvine', 'CA', 'America/Los_Angeles', 33.6405, -117.8443, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'ucla', 'UCLA', 'Los Angeles', 'CA', 'America/Los_Angeles', 34.0689, -118.4452, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-riverside', 'UC Riverside', 'Riverside', 'CA', 'America/Los_Angeles', 33.9737, -117.3281, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-san-diego', 'UC San Diego', 'La Jolla', 'CA', 'America/Los_Angeles', 32.8801, -117.2340, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-santa-barbara', 'UC Santa Barbara', 'Santa Barbara', 'CA', 'America/Los_Angeles', 34.4140, -119.8489, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-santa-cruz', 'UC Santa Cruz', 'Santa Cruz', 'CA', 'America/Los_Angeles', 36.9914, -122.0609, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'utah', 'University of Utah', 'Salt Lake City', 'UT', 'America/Denver', 40.7649, -111.8421, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'utah-state', 'Utah State University', 'Logan', 'UT', 'America/Denver', 41.7420, -111.8097, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'vanderbilt', 'Vanderbilt University', 'Nashville', 'TN', 'America/Chicago', 36.1447, -86.8027, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'vermont', 'University of Vermont', 'Burlington', 'VT', 'America/New_York', 44.4779, -73.1965, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'villanova', 'Villanova University', 'Villanova', 'PA', 'America/New_York', 40.0357, -75.3378, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'virginia', 'University of Virginia', 'Charlottesville', 'VA', 'America/New_York', 38.0336, -78.5080, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'virginia-tech', 'Virginia Tech', 'Blacksburg', 'VA', 'America/New_York', 37.2284, -80.4234, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'wake-forest', 'Wake Forest University', 'Winston-Salem', 'NC', 'America/New_York', 36.1346, -80.2769, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'washington', 'University of Washington', 'Seattle', 'WA', 'America/Los_Angeles', 47.6553, -122.3035, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'washington-state', 'Washington State University', 'Pullman', 'WA', 'America/Los_Angeles', 46.7319, -117.1542, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'west-virginia', 'West Virginia University', 'Morgantown', 'WV', 'America/New_York', 39.6350, -79.9545, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'western-michigan', 'Western Michigan University', 'Kalamazoo', 'MI', 'America/Detroit', 42.2830, -85.6117, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'wichita-state', 'Wichita State University', 'Wichita', 'KS', 'America/Chicago', 37.7188, -97.2926, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'william-mary', 'William and Mary', 'Williamsburg', 'VA', 'America/New_York', 37.2707, -76.7075, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'wisconsin', 'University of Wisconsin-Madison', 'Madison', 'WI', 'America/Chicago', 43.0766, -89.4125, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'wyoming', 'University of Wyoming', 'Laramie', 'WY', 'America/Denver', 41.3149, -105.5666, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'xavier', 'Xavier University', 'Cincinnati', 'OH', 'America/New_York', 39.1494, -84.4737, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'yale', 'Yale University', 'New Haven', 'CT', 'America/New_York', 41.3163, -72.9223, CURRENT_TIMESTAMP)
ON CONFLICT (slug) DO UPDATE SET 
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  "updatedAt" = CURRENT_TIMESTAMP;

-- Show results
SELECT COUNT(*) as total_campuses FROM campuses;
SELECT name, city, state, latitude, longitude FROM campuses WHERE latitude IS NOT NULL ORDER BY state, name LIMIT 20;
