# Podfile for CampusCuts iOS App

platform :ios, '16.0'

target 'CampusCuts' do
  use_frameworks!

  # Stripe for payments
  pod 'Stripe', '~> 23.0'
  
  # Firebase for push notifications
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  
  # Networking
  pod 'Alamofire', '~> 5.8'
  
  # Image loading and caching
  pod 'Kingfisher', '~> 7.10'

  target 'CampusCutsTests' do
    inherit! :search_paths
  end

  target 'CampusCutsUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end

